# No Exception Authorized
So, where do we have exceptions?

```java
public final class Bank {
    ...
    public Money convert(Money money, Currency to) throws MissingExchangeRateException {
        if (!canConvert(money, to)) {
            throw new MissingExchangeRateException(money.currency(), to);
        }
        return convertSafely(money, to);
    }
    ...
}

public final class Portfolio {
    ...

    private ConversionResult convertMoney(Bank bank, Money money, Currency toCurrency) {
        try {
            return new ConversionResult(bank.convert(money, toCurrency));
        } catch (MissingExchangeRateException missingExchangeRateException) {
            return new ConversionResult(missingExchangeRateException);
        }
    }
    ...
}
```

We have a few options to remove exceptions
  - Use Hollywood principle -> callback functions `onSuccess`, `onFailure`
  - Use a data structure representing computation results : `success` or `failure`

What a coincidence! We have already created a similar structure: `ConversionResult`.

Let's see we can go from there.

## Portfolio
We're going to use the same [Wrap Technique](https://understandlegacycode.com/blog/key-points-of-working-effectively-with-legacy-code/#2-the-wrap-technique)  we used before.

:red_circle: You know the drill by now: as usual, we start with a red test at the `Portfolio` level.

We rename the `evaluate` method into `evaluateWithException`.

```java
@Test
@DisplayName("5 USD + 10 EUR + 4 EUR = 21.8 USD")
void shouldAddMoneyInDollarsAndMultipleAmountInEuros() throws MissingExchangeRatesException {
    var portfolio = portfolioWith(
            dollars(5),
            euros(10),
            euros(4)
    );

    assertThat(portfolio.evaluateWithException(bank, USD))
            .isEqualTo(dollars(21.8));
}

@Test
@DisplayName("Return a failure result in case of missing exchange rates")
void shouldReturnAFailingResultInCaseOfMissingExchangeRates() {
    var portfolio = portfolioWith(
            euros(1),
            dollars(1),
            koreanWons(1)
    );

    assertThat(portfolio.evaluate(bank, EUR)
            .failure())
            .isEqualTo("Missing exchange rate(s): [USD->EUR],[KRW->EUR]");
}
```

:green_circle: We generate a new `evaluate` method from the test with the expected signature.

We need to change `ConversionResult` accessibility as well.

```java
public ConversionResult evaluate(Bank bank, Currency currency) {
    return null;
}

public record ConversionResult(Money money, MissingExchangeRateException missingExchangeRateException) {
    public ConversionResult(Money money) {
        this(money, null);
    }

    public ConversionResult(MissingExchangeRateException missingExchangeRateException) {
        this(null, missingExchangeRateException);
    }

    public boolean isFailure() {
        return missingExchangeRateException != null;
    }

    public boolean isSuccess() {
        return money != null;
    }
}
```

Let's implement the `evaluate` by calling the old one first.

```java
public ConversionResult evaluate(Bank bank, Currency currency) {
    try {
        return new ConversionResult(
                evaluateWithException(bank, currency)
        );
    } catch (MissingExchangeRatesException e) {
        return new ConversionResult(e));
    }
} 
```

At the moment, `ConversionResult` is coupled to a specific exception type, but we'd like to have a bit more flexibility here. We need to adapt it to support `Exception` differently.

Let's use java `generics` for this.

```java
public record ConversionResult<Failure>(Money money, Failure failure) {
    public ConversionResult(Money money) {
        this(money, null);
    }

    public ConversionResult(Failure exception) {
        this(null, exception);
    }

    public boolean isFailure() {
        return failure != null;
    }

    public boolean isSuccess() {
        return money != null;
    }
}
```

We need to adapt our `Portfolio` to use the Generic type everywhere

```java
public final class Portfolio {
    ...
    public ConversionResult<String> evaluate(Bank bank, Currency currency) {
        try {
            return new ConversionResult<>(evaluateWithException(bank, currency)
            );
        } catch (MissingExchangeRatesException e) {
            return new ConversionResult<>(e.getMessage());
        }
    }

    private boolean containsFailure(List<ConversionResult<MissingExchangeRateException>> convertedMoneys) {
        return convertedMoneys.stream().anyMatch(ConversionResult::isFailure);
    }

    private List<ConversionResult<MissingExchangeRateException>> convertAllMoneys(Bank bank, Currency toCurrency) {
        return moneys.stream()
                .map(money -> convertMoney(bank, money, toCurrency))
                .toList();
    }

    private MissingExchangeRatesException toMissingExchangeRatesException(List<ConversionResult<MissingExchangeRateException>> convertedMoneys) {
        return new MissingExchangeRatesException(
                convertedMoneys.stream()
                        .filter(ConversionResult::isFailure)
                        .map(ConversionResult::failure)
                        .toList()
        );
    }

    private Money toMoney(List<ConversionResult<MissingExchangeRateException>> convertedMoneys, Currency toCurrency) {
        return new Money(convertedMoneys.stream()
                .filter(ConversionResult::isSuccess)
                .mapToDouble(c -> c.money.amount())
                .sum(), toCurrency);
    }

    private ConversionResult<MissingExchangeRateException> convertMoney(Bank bank, Money money, Currency toCurrency) {
        try {
            return new ConversionResult<>(bank.convert(money, toCurrency));
        } catch (MissingExchangeRateException missingExchangeRateException) {
            return new ConversionResult<>(missingExchangeRateException);
        }
    }

    public record ConversionResult<Failure>(Money money, Failure failure) {
        public ConversionResult(Money money) {
            this(money, null);
        }

        public ConversionResult(Failure exception) {
            this(null, exception);
        }

        public boolean isFailure() {
            return failure != null;
        }

        public boolean isSuccess() {
            return money != null;
        }
    }
} 
```

Our test is now green.

:large_blue_circle: Let's refactor by implementing the new evaluation logic.

- We implement the new evaluation logic
  - Because we will have to change method signature we choose to duplicate the code

```java
public ConversionResult<String> evaluate(Bank bank, Currency toCurrency) {
    var convertedMoneys = convertAllMoneys(bank, toCurrency);

    if (containsFailure(convertedMoneys)) {
        return new ConversionResult<>(
                convertedMoneys.stream()
                        .filter(ConversionResult::isFailure)
                        .map(ConversionResult::failure)
                        .map(e -> String.format("[%s]", e.getMessage()))
                        .collect(Collectors.joining(",", "Missing exchange rate(s): ", ""))
        );
    }
    return new ConversionResult<>(new Money(convertedMoneys.stream()
            .filter(ConversionResult::isSuccess)
            .mapToDouble(c -> c.money.amount())
            .sum(), toCurrency));
}
```

Let's adapt a first test to use new `Evaluate` method as code is no longer throwing an `Exception`.

We need to access `money` from `ConversionResult`.

```java
@Test
@DisplayName("5 USD + 10 USD = 15 USD")
void shouldAddMoneyInTheSameCurrency() {
    var portfolio = portfolioWith(
            dollars(5),
            dollars(10)
    );

    assertThat(portfolio.evaluate(bank, USD)
            .money())
            .isEqualTo(dollars(15));
}
```

:large_blue_circle: Now is the time to remove dead code and duplication
- Method `evaluateWithException` is no longer used, so aren't its related private methods: `toMissingExchangeRatesException`, `toMoney`.
- The `MissingExchangeRatesException` is no longer used either.
    

We can make some clean up: 
- Extract inner public class in its own file
- Extract some methods from the `evaluate` one

```java
public ConversionResult<String> evaluate(Bank bank, Currency toCurrency) {
    var convertedMoneys = convertAllMoneys(bank, toCurrency);

    return containsFailure(convertedMoneys)
            ? new ConversionResult<>(toFailure(convertedMoneys))
            : new ConversionResult<>(sumConvertedMoney(convertedMoneys, toCurrency));
}

private Money sumConvertedMoney(List<ConversionResult<MissingExchangeRateException>> convertedMoneys, Currency toCurrency) {
    return new Money(convertedMoneys.stream()
            .filter(ConversionResult::isSuccess)
            .mapToDouble(c -> c.money().amount())
            .sum(), toCurrency);
}

private String toFailure(List<ConversionResult<MissingExchangeRateException>> convertedMoneys) {
    return convertedMoneys.stream()
            .filter(ConversionResult::isFailure)
            .map(ConversionResult::failure)
            .map(e -> String.format("[%s]", e.getMessage()))
            .collect(Collectors.joining(",", "Missing exchange rate(s): ", ""));
}
```

:large_blue_circle: We can express success and failure in more visual way so let's try.

```java
public ConversionResult<String> evaluate(Bank bank, Currency toCurrency) {
    var convertedMoneys = convertAllMoneys(bank, toCurrency);

    return containsFailure(convertedMoneys)
            ? ConversionResult.fromFailure(toFailure(convertedMoneys))
            : ConversionResult.fromSuccess(sumConvertedMoney(convertedMoneys, toCurrency));
}

public record ConversionResult<Failure>(Money money, Failure failure) {
    private ConversionResult(Money money) {
        this(money, null);
    }

    private ConversionResult(Failure exception) {
        this(null, exception);
    }

    public static <F> ConversionResult<F> fromFailure(F failure) {
        return new ConversionResult<>(failure);
    }

    public static <F> ConversionResult<F> fromSuccess(Money money) {
        return new ConversionResult<>(money);
    }

    public boolean isFailure() {
        return failure != null;
    }

    public boolean isSuccess() {
        return money != null;
    }
}
```

We have successfully removed one `Exception` but the work is not over yet. 

We need to do the same at the `Bank` level.

## Bank
The strategy we used worked quite well. So, same idea here.

:red_circle: Red.

```java
@Test
@DisplayName("Return a failure result in case of missing exchange rate")
void shouldReturnAFailingResultInCaseOfMissingExchangeRate() {
    assertThat(bank.convert(euros(10), KRW)
            .failure())
            .isEqualTo("EUR->KRW");
}
```

We rename the existing `convert` to `convertWithException` and generate the code from our test.

```java
public Money convertWithException(Money money, Currency to) throws MissingExchangeRateException {
    if (!canConvert(money, to)) {
        throw new MissingExchangeRateException(money.currency(), to);
    }
    return convertSafely(money, to);
}

public ConversionResult<String> convert(Money money, Currency to) {
    return null;
}
```

:green_circle: Green.

```java
public Money convertWithException(Money money, Currency to) throws MissingExchangeRateException {
    if (!canConvert(money, to)) {
        throw new MissingExchangeRateException(money.currency(), to);
    }
    return convertSafely(money, to);
}

public ConversionResult<String> convert(Money money, Currency to) {
    try {
        return fromSuccess(convertWithException(money, to));
    } catch (MissingExchangeRateException e) {
        return fromFailure(e.getMessage());
    }
} 
```

:large_blue_circle: Refactor.

```java
public ConversionResult<String> convert(Money money, Currency to) {
    return canConvert(money, to)
            ? fromSuccess(convertSafely(money, to))
            : fromFailure(String.format("%s->%s", money.currency(), to));
} 
```

We can now adapt our callers to use the new `convert`: `Portfolio` and `BankTest`
  - Really easy in the tests
  - We have some work to refactor the `Porftolio` so we start by changing the `convertAllMoneys` method

```java
private List<ConversionResult<String>> convertAllMoneys(Bank bank, Currency toCurrency) {
    return moneys.stream()
            .map(money -> bank.convert(money, toCurrency))
            .toList();
}

// Delete it -> not needed anymore
private ConversionResult<MissingExchangeRateException> convertMoney(Bank bank, Money money, Currency toCurrency) {
    try {
        return fromSuccess(bank.convertWithException(money, toCurrency));
    } catch (MissingExchangeRateException missingExchangeRateException) {
        return fromFailure(missingExchangeRateException);
    }
}
```

We adapt methods in `Portfolio` to only use `ConversionResult<String>`.

```java
public ConversionResult<String> evaluate(Bank bank, Currency toCurrency) {
    var convertedMoneys = convertAllMoneys(bank, toCurrency);

    return containsFailure(convertedMoneys)
            ? fromFailure(toFailure(convertedMoneys))
            : fromSuccess(sumConvertedMoney(convertedMoneys, toCurrency));
}

private Money sumConvertedMoney(List<ConversionResult<String>> convertedMoneys, Currency toCurrency) {
    return new Money(convertedMoneys.stream()
            .filter(ConversionResult::isSuccess)
            .mapToDouble(c -> c.money().amount())
            .sum(), toCurrency);
}

private String toFailure(List<ConversionResult<String>> convertedMoneys) {
    return convertedMoneys.stream()
            .filter(ConversionResult::isFailure)
            .map(ConversionResult::failure)
            .map(e -> String.format("[%s]", e))
            .collect(Collectors.joining(",", "Missing exchange rate(s): ", ""));
}

private boolean containsFailure(List<ConversionResult<String>> convertedMoneys) {
    return convertedMoneys
            .stream()
            .anyMatch(ConversionResult::isFailure);
}

private List<ConversionResult<String>> convertAllMoneys(Bank bank, Currency toCurrency) {
    return moneys.stream()
            .map(money -> bank.convert(money, toCurrency))
            .toList();
} 
```

We can now remove the `convertWithException` method in `Bank` and `MissingExchangeRateException`

## Reflect
![No exception](../../docs/img/no-exception.png)

Any improvement ideas?
  - The way we use the `ConversionResult` is not safe for example...
  - Maybe there is an alternative to use safer data structure
  - You can discover more about the `Monad` concepts and how to apply them in java with [vavr](https://www.vavr.io/)